name: coding-agent

on:
  issue_comment:
    types: [created, edited]  # runs when someone comments
  workflow_dispatch:

permissions:
  contents: write        # create branch & push
  pull-requests: write   # open PR
  issues: write          # (optional) post back a comment

jobs:
  run:
    if: startsWith(github.event.comment.body, '/agent')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install agent
        run: |
          python -m pip install --upgrade pip
          pip install -r agent/requirements.txt

      - name: Run agent
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          python agent/main.py
